### ISSUE TITLE
New to Python

### ISSUE THREAD

**Issue by mpahuta** [mathiasunberath/DeepDRR#11]
Hi

i would like to generate some DRRs at various angles.

I have been struggling with generating adequate DRRs with plastimatch.

I noticed that you generated a beautiful AP Pelvis DRR with the NIH Cancer Imaging Archive... I was hoping to do the same but generate a lateral DRR.

I was wondering if you might be able to share your code, and the specific dataset you used? 

I am not very skilled at python and would greatly appreciate your help.

Thank you

**Comment by mpahuta** [comment]
Mathias Answer:

Thank you for reaching out.

Here’s some guidance on how to do it.

You can find reference to the CT scans we used for those images here: https://github.com/mathiasunberath/AnatomicalLandmarks
Just download one or use any other high resolution, low noise CT scan you may have (if you do this, you will need to verify that the dicom load function works as expected, I will not elaborate on that)
Navigate to https://github.com/mathiasunberath/DeepDRR/blob/master/example_projector_tool.py and inspect the main method in L.81
Specify the path to your CT volume (L.90)
Specify your imaging geometry (L.83)
Specify the save path (L.93)
Specify imaging parameters (L.94 ff)
The X-ray source is assumed to move on a sphere centered in the origin. Specify angle ranges theta and phi (IIRC 90/90 coincides with AP of a supine patient with CRA/CAU along z-axis), then specify the spacing. The angle range will be sampled in this spacing: this is because DeepDRR is designed to create large amounts of images for training of ML algorithms. If you only want one image, select the spacing such that it only fits once within the range.
You will need to adjust the origin (particularly Z) to shift your volume up/down. Same can be done with x/y to position the CT properly within the cone-beam.
Depending on the attenuation of your CT, you  may need to adjust the number of photons
 

Known problems the solutions of which you will find by inspecting previous issues on the GitHub:

Dynamic range: Lateral images will likely pass through a lot of attenuating tissue and air at the same time. I am sure you are aware of window/leveling to visualize the structures better. This is necessary because we do not currently implement collimation
Segmentation: DeepDRR is multi-material, polychromatic. This means that somewhere along the pipeline we segment the CT into multiple materials. This is usually accomplished by thresholding (although we do provide a pre-trained CNN to do the task which is discouraged for testing). It usually makes sense to inspect the material decomposition to make sure the thresholds set were reasonable. It is possible to adjust them manually
Be vary of input errors. Wrong origin, spacing, HU scaling intercept, etc. If something unexpected happens, this is usually a good place to look. We fixed these issues as we found them, but depending on your data there may be more.
 

Hope this helps.

**Comment by mathiasunberath** [comment]
Thank you for sharing our conversation!
