### ISSUE TITLE
DeepDRR in AWS?

### ISSUE THREAD

**Issue by mpahuta** [mathiasunberath/DeepDRR#12]
Hi

I would like to use DeepDRR but I do not have an NVIDA GPU, so I was unable to complete the Windows instructions listed on the website.

I was wondering if it would be possible to run the code on AWS. I was looking at https://aws.amazon.com/marketplace/pp/Amazon-Web-Services-AWS-Deep-Learning-AMI-Ubuntu-1/B07Y43P7X5, would this instance work?

If yes, would it be possible to get some instructions on how to configure DeepDRR with this instance?

**Comment by sainatarajan** [comment]
@mpahuta Maybe you can try running it in google-colab if you're just testing the repo.

**Comment by mpahuta** [comment]
OK. I've never used google-colab before. is there a preconfigured set-up for this?

**Comment by sainatarajan** [comment]
@mpahuta There isn't any. Try to run the entire repo from colab.
