### ISSUE TITLE
DeepDRR - Google Colab

### ISSUE THREAD

**Issue by mpahuta** [mathiasunberath/DeepDRR#13]
Hi,

I am trying to run DeepDRR on Google Colab. 

I copied the entire DeepDRR github directory structure to "Colab Notebooks" in GoogleDrive.

I create a new notebook. I then Edit --> Notebook Setting --> Runtime type = Python 3 and Hardware accelerator = GPU.

I then use the following code:
```
!pip install -q pydicom

from google.colab import drive
drive.mount('/content/gdrive', force_remount=True)

!python gdrive/My\ Drive/Colab\ Notebooks/DRR/example_projector.py
```
I get an error [error](https://github.com/mathiasunberath/DeepDRR/files/4483175/error.txt) which is attached. I think the main issue is that "`pycuda.driver.CompileError: nvcc preprocessing of /tmp/tmp65qx05s_.cu failed`"

I was hoping I could get help resolving this issue so that I can run the example in Google Colab.

Thank you

**Comment by gaocong13** [comment]
Hi, did you install pycuda which is a required dependency for DeepDRR? It looks like an issue with nvcc driver, it would be helpful to post your CUDA and torch version.

**Comment by sainatarajan** [comment]
For anyone trying it to run in google colab, you can have a look at my code here: 
[DeepDRR.ipynb](https://colab.research.google.com/drive/1d5kzRYYXIpDwl1xsfkbPSrm-vDHwOh8z)

**Comment by mpahuta** [comment]
CUDA = 10.1.243
Torch = 1.4.0

I am still getting the same error. I suppose this could be because I am not using CUDA 8? Any experience changing the CUDA version?

```
53         from pycuda.driver import CompileError
     54         raise CompileError("nvcc preprocessing of %s failed" % source_path,
---> 55                            cmdline, stderr=stderr)
     56 
     57     # sanity check

CompileError: nvcc preprocessing of /tmp/tmps7bqxqux.cu failed
[command: nvcc --preprocess -arch sm_60 -I/content/gdrive/My Drive/Proj/cubic -I/usr/local/lib/python3.6/dist-packages/pycuda/cuda /tmp/tmps7bqxqux.cu --compiler-options -P]
[stderr:
b'/tmp/tmps7bqxqux.cu:3:22: fatal error: cubicTex3D.cu: No such file or directory\n             #include <cubicTex3D.cu>\n                      ^~~~~~~~~~~~~~~\ncompilation terminated.\n']`
```

**Comment by gaocong13** [comment]
I would suggest trying CUDA 9.0

**Comment by mpahuta** [comment]
Hi,

I've tried running with CUDA 9.0, and 9.2. Code doesn't run with either. 

What I did was run the code below prior to running the code in DeepDRR.ipynb,

I did confirm that CUDA was downgraded... hoping for some other suggestions...

```
!wget https://developer.nvidia.com/compute/cuda/9.0/Prod/local_installers/cuda-repo-ubuntu1604-9-0-local_9.0.176-1_amd64-deb
!dpkg -i cuda-repo-ubuntu1604-9-0-local_9.0.176-1_amd64-deb
!apt-key add /var/cuda-repo-9-0-local/7fa2af80.pub
!apt-get update
!apt-get install cuda=9.0.176-1
```

or

```
!wget https://developer.nvidia.com/compute/cuda/9.2/Prod2/local_installers/cuda-repo-ubuntu1710-9-2-local_9.2.148-1_amd64
!dpkg -i cuda-repo-ubuntu1710-9-2-local_9.2.148-1_amd64
!apt-key add /var/cuda-repo-9-2-local/7fa2af80.pub
!apt-get update
!apt-get install cuda=9.2.148-1
```

**Comment by mathiasunberath** [comment]
Did you switch the runtime from CPU to GPU? Take a look here for how to do that: https://medium.com/@iphoenix179/running-cuda-c-c-in-jupyter-or-how-to-run-nvcc-in-google-colab-663d33f53772

**Comment by mpahuta** [comment]
Yes, I am using GPU. Also using Python 3

**Comment by mathiasunberath** [comment]
I assume you saw this comment in the readme and have followed the steps described there: 

The codebase provided here was not developed with Google Colaboratory in mind, but our userbase has found small tweaks to the code to make it work in Colab. Kindly refer to https://github.com/mathiasunberath/DeepDRR/issues/6 and https://github.com/mathiasunberath/DeepDRR/issues/5 for the required changes

**Comment by mpahuta** [comment]
Yes, I made those changes as well

**Comment by mathiasunberath** [comment]
Taking a closer look, the compiler tells you: 

> fatal error: cubicTex3D.cu: No such file or directory 

This is a DeepDRR source file, located in ./cubic/ subfolder. Your system seems unable to find this file. To me, this suggests that something is wrong with your directory setup or linking which will be hard for us to remotely debug.

**Comment by mpahuta** [comment]
Hi,

Thank you for looking at this issue in detail.

I think I got it to work with the simple phanton... should the output just be white figures in "new-dicom-data"

What got the program to run was
```
!pip install pycuda
!pip install pydicom
from google.colab import drive
drive.mount('/content/gdrive', force_remount=True)

import sys
sys.path.append('/content/gdrive/My Drive/DeepDRR-master/')

!python gdrive/My\ Drive/DeepDRR-master/example_projector2.py
```

The issue was that
- in the "sys.path.append" line you should use "/My Drive/"
- In the "!python" line you should use "My\ Drive"

**Comment by mathiasunberath** [comment]
Good to hear you figured it out and thank you for sharing the solution.
