### ISSUE TITLE
Windowing/Leveling

### ISSUE THREAD

**Issue by mpahuta** [mathiasunberath/DeepDRR#16]
Hi,

Regarding windowing/leveling mentioned in [Issue 11](https://github.com/mathiasunberath/DeepDRR/issues/11l)

Is there a way to adjust this within the DeepDRR code? Or this is to be done on using image processing software after running?

**Comment by mathiasunberath** [comment]
No, DeepDRR has no such functionality as it is not primarily a visualization software. I would recommend checking out ImageJ (FIJI distribution) available here https://imagej.net/Fiji .
