### ISSUE TITLE
network weights file is corrupted

### ISSUE THREAD

**Issue by gokceay** [mathiasunberath/DeepDRR#17]
Hi,

I would like to try your deepDRR code but the segmentation network weights file from dropbox is corrupted. I tried many times. Would you help me regarding this issue?

**Comment by mathiasunberath** [comment]
@gaocong13 @Jan-Nico any chance you can take a look?

**Comment by gokceay** [comment]
I downloaded and used the network weights even though dropbox says that there is a problem. The network weights worked. Thank you for your fast response ^_^ Best regards
