### ISSUE TITLE
can't convert cuda:0 device type tensor to numpy

### ISSUE THREAD

**Issue by gokceay** [mathiasunberath/DeepDRR#18]
Hi,
I got an error like 
$python3 example_projector.py 
generating  6 matrices
segmenting volume with Vnet
loaded segmentation network
(3, 512, 512, 256)
1
Traceback (most recent call last):
  File "example_projector.py", line 97, in <module>
    main()
  File "example_projector.py", line 93, in main
    generate_projections_on_sphere(dicompath,save_path,min_theta,max_theta,min_phi,max_phi,spacing_theta,spacing_phi,photon_count,camera,spectrum,origin=origin,scatter=False)
  File "example_projector.py", line 23, in generate_projections_on_sphere
    volume, materials, voxel_size = load_dicom(volume_path, use_thresholding_segmentation=False)
  File "/home/ubuntu/DeepDRR/load_dicom.py", line 68, in load_dicom
    materials = conv_hu_to_materials(volume)
  File "/home/ubuntu/DeepDRR/load_dicom.py", line 108, in conv_hu_to_materials
    materials = segmentation_network.segment(hu_values)
  File "/home/ubuntu/DeepDRR/segmentation.py", line 60, in segment
    output_tensor = np.array(self.model.forward(Variable(curren_block_tensor,requires_grad = False)).data)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/torch/tensor.py", line 492, in __array__
    return self.numpy()
TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

 and changed these 3 lines

curren_block_tensor = torch.from_numpy(presegmentation).cuda()
curren_block_tensor = torch.unsqueeze(curren_block_tensor,0)
output_tensor = np.array(self.model.forward(Variable(curren_block_tensor,requires_grad = False)).data)

to these

curren_block_tensor = torch.from_numpy(presegmentation)
curren_block_tensor = torch.unsqueeze(curren_block_tensor,0).cuda()
output_tensor = np.array(self.model.forward(Variable(curren_block_tensor,requires_grad = False)).cpu().data)

and run the example_projector.py file with a chest CT data. (from LIDC-IDRI dataset)
and I got the attached files as a result. I am not sure about that I did the correct adjustments to have more realistic result. What should I do to improve my results?
![DRR00004](https://user-images.githubusercontent.com/11376483/82159957-a04ce180-989a-11ea-9863-57129d9a761a.jpg)
![DRR00002](https://user-images.githubusercontent.com/11376483/82159962-a9d64980-989a-11ea-9414-813eb1a2aa17.jpg)
![DRR00005](https://user-images.githubusercontent.com/11376483/82159969-b5297500-989a-11ea-90e1-dd5e0685707e.jpg)
![DRR00003](https://user-images.githubusercontent.com/11376483/82159981-c1adcd80-989a-11ea-8c48-d5a978f232d1.jpg)
![DRR00001](https://user-images.githubusercontent.com/11376483/82159989-ca9e9f00-989a-11ea-80e1-3e909d02133d.jpg)
![DRR00000](https://user-images.githubusercontent.com/11376483/82159996-d5f1ca80-989a-11ea-870b-c017e796ab19.jpg)

**Comment by mathiasunberath** [comment]
The results do not look too bad to me - I would suggest you investigate the image quality after log correction to reduce the dynamic range of the images. This will allow you to better understand whether the images contain the information you are looking for. If you suspect that the CNN may not perform to your liking, I would suggest you start with threshold-based material decomposition and tune the threshold to your dataset. This will give you better understanding of what can be accomplished. Finally, from the images it appears that the CT scan you use for simulation may be quite low resolution. You will find lots of similar questions and answers in the previously addressed issues and I would encourage you to take a look there, too.

**Comment by gokceay** [comment]
Thanks a lot for the detailed and response Prof. Unberath. I will try your suggestions ^_^
