### ISSUE TITLE
Running DeepDRR for producing X-ray images from arbitrary CT

### ISSUE THREAD

**Issue by smshams** [mathiasunberath/DeepDRR#20]
Hi,

I successfully ran the example on google colab and I have two questions:
1- The generated images in the generated_image folder does not seem OK. 
2- How can I produce simulated X-ray from the results

Thank you all for your helpful comments

**Comment by mathiasunberath** [comment]
I assume you were able to solve the problem. If there's anything you need help with, you can reopen and also review previous issues. Thanks!

**Comment by smshams** [comment]
Thank you!

**Comment by MahmoudHigazy** [comment]
> Thank you!

How did you solve the problem?

**Comment by smshams** [comment]
That was an easy problem. In code, six different slices are generated, so we should check all the slices. For my CT images, slices 3:6 looked fine.

**Comment by MahmoudHigazy** [comment]
> That was an easy problem. In code, six different slices are generated, so we should check all the slices. For my CT images, slices 3:6 looked fine.

![image](https://user-images.githubusercontent.com/24832145/91872995-d3b05200-ec78-11ea-9f58-047e513b7995.png)

this is the output for image 3, it looks weird
