### ISSUE TITLE
About the function "conv_hu_to_density"

### ISSUE THREAD

**Issue by PxinLi** [mathiasunberath/DeepDRR#4]
Hi!

Thank you for sharing the code framework.
I have a question about some values in the 'conv_hu_to_density' function. 
![image](https://user-images.githubusercontent.com/15571287/53472145-d3dafa80-3aa1-11e9-94fe-1d701b4142ea.png)
0.0005886
0.001029
1.030
Are they fixed? If it's not fixed, how can I get this number on my data?

Thanks.

Peixin Li

**Comment by mathiasunberath** [comment]
Hello.
These values are fixed. Further information here: http://scipp.ucsc.edu/outreach/hartmut/radiobio/pCT_lit/Schneider%20U%201996.pdf 
and here: http://www.k-wave.org/documentation/hounsfield2density.php
