### ISSUE TITLE
Path problem to segmentation network weights file

### ISSUE THREAD

**Issue by sainatarajan** [mathiasunberath/DeepDRR#5]
Hi, thanks for this great library.
We tried the DeepDRR library on Google Colab and there arose a number of issues. We have found the solutions to most of them and we would like to post it here so that it could be of benefit to others.

**Issue**: In the file segmentation.py and inside the constructor, the field **model_path** is set to search for the segmentation network weights file in the current directory. So, what we did was to modify the field’s value to set the path in google drive where the file was stored. When we executed the code after modification, it resulted in the Error: No such file or directory.

**Solution**: After much time, we discovered that the error might be due to the optimized pre-compiled code that python was executing instead of the modified python file. These pre-compiled codes are stored in __pycache__ folder inside the DeepDRR. So, all we did was to delete the folder and execute the program once again. This time it worked as expected.

**Comment by mathiasunberath** [comment]
Thanks. This fix is now reflected in the readme.
