### ISSUE TITLE
generating images without readjusting parameters

### ISSUE THREAD

**Issue by Turnman** [mathiasunberath/DeepDRR#9]
Hi Mathias,

I'd like to use your framework to generate training data based on a CT scan covering pelvic and thorax region. As mentioned in #8 I (currently) cannot use the same setting and just run over the whole scan and generate images.

How did you do this for the model described in the paper?

Thanks a lot!

**Comment by mathiasunberath** [comment]
Kindly see my response in https://github.com/mathiasunberath/DeepDRR/issues/8. It should not be necessary to change parameters (other than the photon flux of course) on DRR-basis.
